const DemoLayerSections = [
  {
    id: "german_layer_items",
    caretId: "german-layer-caret",
    label: "Germany Data Demo",
    itemSelector: ".german-layer-item",
    zoomTo: "NorthAfrica",
    infoId: "grants-info-layer",
    type: "group",
  },
  {
    id: "german_layer",
    className: "german_layer",
    name: "german_layer",
    iconColor: "#7b68ee",
    label: "Information",
    topLayerClass: "german-layer",
    iconType: "square",
    isSolid: true,
  },
  {
    id: "german_layer_lines",
    className: "german_layer",
    name: "german_layer_lines",
    iconColor: "#000080",
    label: "Lines",
    topLayerClass: "german-layer",
    iconType: "square",
    isSolid: false,
  },
  {
    id: "global_layer_items",
    caretId: "global-layer-caret",
    label: "Territory",
    itemSelector: ".global-layer-item",
    zoomTo: "NorthAfrica",
    infoId: "grants-info-layer",
    type: "group",
  },
  {
    id: "global_layer",
    className: "global_layer",
    name: "global_layer",
    iconColor: "#e3ed58",
    label: "Information",
    topLayerClass: "global-layer",
    iconType: "square",
    isSolid: true,
  },
  {
    id: "global_layer_lines",
    className: "global_layer",
    name: "global_layer_lines",
    iconColor: "#ff0000",
    label: "Lines",
    topLayerClass: "global-layer",
    iconType: "square",
    isSolid: false,
  },
  //=====================>>>>>
  {
    id: "global_labels_items",
    caretId: "global-labels-caret",
    label: "Global Labels",
    itemSelector: ".global-labels-item",
    zoomTo: "NorthAfrica",
    infoId: "grants-info-labels",
    type: "group",
  },
  /*
  {
    id: "global_labels_points",
    className: "global-labels",
    name: "global_labels_points",
    iconColor: "#ff0000",
    label: "Places",
    topLayerClass: "global-labels",
    iconType: "circle",
    isSolid: true,
  },
  */
  {
    id: "global_labels",
    className: "global-labels",
    name: "global_labels",
    iconColor: "#0b0ee5",
    label: "Labels",
    topLayerClass: "global-labels",
    iconType: "comment-dots",
    isSolid: true,
  }
];

const longIslandLayerSections = [
];
